const loginFieldsForNGO = [
  {
    labelText: "Username",
    labelFor: "Username",
    id: "Username",
    name: "Username",
    type: "Username",
    autoComplete: "Username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
const loginFieldsForRestaurants = [
  {
    labelText: "Username",
    labelFor: "Username",
    id: "Username",
    name: "Username",
    type: "Username",
    autoComplete: "Username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
const signupFieldsForNGO = [
  {
    labelText: "NGO Name",
    labelFor: "NGO name",
    id: "NGO name",
    name: "NGO name",
    type: "text",
    autoComplete: "NGO name",
    isRequired: true,
    placeholder: "NGO name",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },

  {
    labelText: "Address",
    labelFor: "Address",
    id: "Address",
    name: "Address",
    type: "text",
    autoComplete: "Address",
    isRequired: true,
    placeholder: "Address",
  },
  {
    labelText: "State",
    labelFor: "State",
    id: "State",
    name: "State",
    type: "text",
    autoComplete: "State",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "City",
    labelFor: "City",
    id: "City",
    name: "City",
    type: "text",
    autoComplete: "City",
    isRequired: true,
    placeholder: "City",
  },
  {
    labelText: "Phone",
    labelFor: "Phone",
    id: "Phone",
    name: "Phone",
    type: "text",
    autoComplete: "Phone",
    isRequired: true,
    placeholder: "Phone",
  },
];

const signupFieldsForRestaurants = [
  {
    labelText: "Restaurant Name",
    labelFor: "Restaurant name",
    id: "Restaurant name",
    name: "Restaurant name",
    type: "text",
    autoComplete: "Restaurant name",
    isRequired: true,
    placeholder: "Restaurant name",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "Branch ID",
    labelFor: "Branch ID",
    id: "Branch ID",
    name: "Branch ID",
    type: "text",
    autoComplete: "Branch ID",
    isRequired: true,
    placeholder: "Branch ID",
  },
  {
    labelText: "Address",
    labelFor: "Address",
    id: "Address",
    name: "Address",
    type: "text",
    autoComplete: "Address",
    isRequired: true,
    placeholder: "Address",
  },
  {
    labelText: "State",
    labelFor: "State",
    id: "State",
    name: "State",
    type: "text",
    autoComplete: "State",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "City",
    labelFor: "City",
    id: "City",
    name: "City",
    type: "text",
    autoComplete: "City",
    isRequired: true,
    placeholder: "City",
  },
  {
    labelText: "Phone",
    labelFor: "Phone",
    id: "Phone",
    name: "Phone",
    type: "text",
    autoComplete: "Phone",
    isRequired: true,
    placeholder: "Phone",
  },
];

export {
  loginFieldsForNGO,
  loginFieldsForRestaurants,
  signupFieldsForRestaurants,
  signupFieldsForNGO,
};
